### ISSUE TITLE
Questions about Tip selection and grey nodes in this visualization

### ISSUE THREAD

**Issue by CaixiangFan** [iotaledger/iotavisualization#38]
Hi, I am learning IOTA Tangle and find this visualization is very interesting. 
Well, I am not sure what do the grey nodes mean in this Tangle, which appeared sometimes? I noticed that they were not treated as Tips even though no newer transactions approved them at all. Are they just not seen by all nodes, which means unsynchronized? Or what are they?
And what is the stop criteria for Weighted Random Walk? Until reaching a tip?

Very appreciated for any replies.
Thank you.

**Comment by alongalky** [comment]
The transactions are gray because they are "invisible" for a time period of `h` (set to one in the simulation) after they are produced. This simulates the time it takes to perform PoW and propagate the transaction in the network. Note that if we set this to zero, we will be left with a chain rather than a "tangle", since transactions will always choose the latest one.

This is explained in more detail [here](https://blog.iota.org/the-tangle-an-illustrated-introduction-c0a86f994445). Does this answer your question?

**Comment by CaixiangFan** [comment]
Hi, Alon, Thank you for your explanation. It makes sense to me.
